package com.jituileet.inputmethod;

import android.app.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;

/** TV-friendly settings. Every action is reachable with a D-pad/OK remote. */
public class SettingsActivity extends Activity {
    LinearLayout root; boolean zh;
    @Override public void onCreate(Bundle b){super.onCreate(b); zh=Prefs.language(this).equals("zh") || (Prefs.language(this).equals("auto") && Locale.getDefault().getLanguage().equals("zh")); if(getIntent().getBooleanExtra("open_dictionary",false)){ pickDict(); return; } build();}
    private TextView title(String t){TextView v=new TextView(this);v.setText(t);v.setTextSize(20);v.setTextColor(Prefs.dark(this)?0xFFF1F3F4:0xFF202124);v.setPadding(22,24,22,18);return v;}
    private void build(){
        root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setFocusable(true);root.setBackgroundColor(Prefs.dark(this)?0xFF202124:Color.WHITE);setContentView(root);
        root.addView(title(zh?"鸡腿输入法设置":"Drumstick Input Method Settings"));
        addButton(zh?"更改外观":"Appearance",v->appearance());addButton(zh?"更改词库":"Dictionary",v->dictionary());addButton(zh?"语言":"Language",v->language());addButton(zh?"键盘":"Keyboard",v->keyboard());addButton(zh?"使用手机输入":"Use phone input",v->phone());addButton(zh?"打开系统输入法设置":"Open system IME settings",v->startActivity(new Intent(Settings.ACTION_INPUT_METHOD_SETTINGS)));
        TextView about=title("\n鸡腿输入法\nDrumstick Input Method\ncom.jituileet.inputmethod\nAndroid 4.4–14 · Rime");about.setTextSize(14);root.addView(about);
    }
    private void addButton(String s,View.OnClickListener l){Button b=new Button(this);b.setAllCaps(false);b.setText(s);b.setTextSize(17);b.setFocusable(true);b.setOnClickListener(l);root.addView(b,new LinearLayout.LayoutParams(-1,64));}
    private AlertDialog dialog(String title, View body){AlertDialog d=new AlertDialog.Builder(this).setTitle(title).setView(body).setNegativeButton(zh?"返回":"Back",null).create();d.setOnShowListener(x->{Button n=d.getButton(AlertDialog.BUTTON_NEGATIVE);if(n!=null)n.setFocusable(true);});return d;}
    private void appearance(){ final String[] colors={"默认浅灰","蓝灰","绿色","紫色","黑色"};final int[] vals={0xFFEBECF0,0xFFE6EDF5,0xFFE6F1EE,0xFFECE7F5,0xFF202124};LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);for(int i=0;i<colors.length;i++){final int k=i;Button b=new Button(this);b.setText(zh?colors[i]:new String[]{"Default light gray","Blue gray","Green","Purple","Black"}[i]);b.setAllCaps(false);b.setFocusable(true);b.setOnClickListener(v->{Prefs.color(this,vals[k]);recreate();});box.addView(b,new LinearLayout.LayoutParams(-1,58));}Switch dark=new Switch(this);dark.setText(zh?"深色模式":"Dark mode");dark.setFocusable(true);dark.setChecked(Prefs.dark(this));box.addView(dark);Button reset=new Button(this);reset.setText(zh?"恢复默认外观":"Restore default appearance");reset.setFocusable(true);reset.setOnClickListener(v->{Prefs.color(this,0xFFEBECF0);Prefs.dark(this,false);recreate();});box.addView(reset);dialog(zh?"更改外观":"Appearance",box).show();}
    private void dictionary(){final ArrayList<String> items=new ArrayList<>();items.add(zh?"输入法自带词库":"Built-in dictionary");File dir=new File(getFilesDir(),"dicts");if(dir.exists()&&dir.listFiles()!=null)for(File f:dir.listFiles())items.add(f.getName());LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);for(String item:items){final String name=item;Button b=new Button(this);b.setText(name);b.setAllCaps(false);b.setFocusable(true);b.setOnClickListener(v->{Prefs.dict(this,name);try{RimeData.selectDictionary(this,name);}catch(Exception ignored){}sendReload();Toast.makeText(this,zh?"词库已切换":"Dictionary selected",Toast.LENGTH_SHORT).show();});box.addView(b,new LinearLayout.LayoutParams(-1,60));}Button upload=new Button(this);upload.setText(zh?"上传词库文件（.dict.yaml）":"Upload dictionary (.dict.yaml)");upload.setFocusable(true);upload.setOnClickListener(v->pickDict());box.addView(upload,new LinearLayout.LayoutParams(-1,60));dialog(zh?"更改词库":"Dictionary",box).show();}
    private void pickDict(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("text/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,88);}
    @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r!=88||c!=RESULT_OK||data==null)return;try{Uri u=data.getData();InputStream in=getContentResolver().openInputStream(u);ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))>0)out.write(b,0,n);in.close();String text=new String(out.toByteArray(),"UTF-8");if(text.trim().isEmpty()){Toast.makeText(this,zh?"该词库文件没有任何内容，请尝试重新上传":"The dictionary file is empty. Please upload it again.",Toast.LENGTH_LONG).show();return;}boolean validHeader=text.matches("(?s).*^name:\\s*[^\\s#]+.*")&&text.contains("---");boolean hasEntry=false;for(String line:text.split("\\r?\\n")){String t=line.trim();if(!t.isEmpty()&&!t.startsWith("#")&&!t.equals("---")&&!t.equals("...")&&!t.contains(":")){hasEntry=true;break;}}if(!validHeader||!hasEntry){Toast.makeText(this,zh?"你上传的词库文件是错误的，请尝试更换一个文件":"The dictionary file is invalid. Please try another file.",Toast.LENGTH_LONG).show();return;}File dir=new File(getFilesDir(),"dicts");dir.mkdirs();String name=String.valueOf(u.getLastPathSegment()).replaceAll("[^A-Za-z0-9._-]","_");if(!name.endsWith(".dict.yaml"))name+=".dict.yaml";File f=new File(dir,name);try(FileOutputStream fo=new FileOutputStream(f)){fo.write(out.toByteArray());}RimeData.installDictionary(this,name,out.toByteArray());Prefs.dict(this,name);sendReload();Toast.makeText(this,zh?"词库上传成功":"Dictionary uploaded",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,zh?"你上传的词库文件是错误的，请尝试更换一个文件":"The dictionary file is invalid. Please try another file.",Toast.LENGTH_LONG).show();}}
    private void language(){String[] a={"中文（简体）","English","跟随系统"};int checked=Prefs.language(this).equals("zh")?0:Prefs.language(this).equals("en")?1:2;AlertDialog d=new AlertDialog.Builder(this).setTitle(zh?"语言":"Language").setSingleChoiceItems(a,checked,(x,w)->{Prefs.language(this,w==0?"zh":w==1?"en":"auto");sendReload();x.dismiss();recreate();}).setNegativeButton(zh?"返回":"Back",null).create();d.show();}
    private void keyboard(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);Switch sw=new Switch(this);sw.setText(zh?"键盘输入":"Keyboard input");sw.setChecked(Prefs.keyboard(this));sw.setFocusable(true);box.addView(sw);Switch notice=new Switch(this);notice.setText(zh?"实体键盘提示":"Physical keyboard notice");notice.setChecked(Prefs.hardwareNotice(this));notice.setFocusable(true);box.addView(notice);AlertDialog d=dialog(zh?"键盘":"Keyboard",box);d.setOnShowListener(x->{sw.setOnCheckedChangeListener((v,on)->Prefs.keyboard(this,on));notice.setOnCheckedChangeListener((v,on)->Prefs.hardwareNotice(this,on));});d.show();}
    private void phone(){LinearLayout box=new LinearLayout(this);box.setPadding(24,12,24,8);box.setOrientation(LinearLayout.VERTICAL);Switch sw=new Switch(this);sw.setText(zh?"使用手机输入":"Use phone input");sw.setChecked(Prefs.phone(this));sw.setFocusable(true);box.addView(sw);TextView info=title(zh?"开启后会显示电视本地连接地址。请确保手机和电视连接同一 Wi-Fi。":"When enabled, the TV local address is shown. Keep phone and TV on the same Wi-Fi.");info.setTextSize(14);box.addView(info);TextView url=title("");url.setTextSize(16);box.addView(url);if(Prefs.phone(this)){PhoneInputServer ps=new PhoneInputServer(this,t->{});ps.start();url.setText(ps.getUrl());}sw.setOnCheckedChangeListener((v,on)->{Prefs.phone(this,on);if(on){PhoneInputServer ps=new PhoneInputServer(this,t->{});ps.start();url.setText(ps.getUrl());}else url.setText("");});dialog(zh?"手机输入":"Phone input",box).show();}
    private void sendReload(){sendBroadcast(new Intent("com.jituileet.inputmethod.RELOAD_RIME").setPackage(getPackageName()));}
}
